### ISSUE TITLE
invalid lexemes in orthography profiles

### ISSUE THREAD

**Issue by LinguList** [lexibank/cals#1]
I just updated the orthoprofile, as it was very weird, with 10000s of duplicated lines. The automated one is better, but needs again to be checked.

**Comment by xrotwang** [comment]
I think I started out with the full set of BIPA and aliases turned into an orthography profile - hence the many duplicates.

**Comment by LinguList** [comment]
Given that it's just 150 or so segments now, it should be a no-brainer to manually go through it. We just have to divide work amon g people in the calc group, and maybe if we find hiwis, this can also help.

**Comment by SimonGreenhill** [comment]
There's a number of replacement glyphs showing here too.
